<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountryflagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        \DB::statement("ALTER TABLE countries ADD flag_url VARCHAR(255) NOT NULL AFTER emoji");

        $flags = [
            "AD" => "https://flagpedia.net/data/flags/w1160/ad.webp",
            "AE" => "https://flagpedia.net/data/flags/w1160/ae.webp",
            "AF" => "https://flagpedia.net/data/flags/w1160/af.webp",
            "AG" => "https://flagpedia.net/data/flags/w1160/ag.webp",
            "AI" => "https://flagpedia.net/data/flags/w1160/ai.webp",
            "AL" => "https://flagpedia.net/data/flags/w1160/al.webp",
            "AM" => "https://flagpedia.net/data/flags/w1160/am.webp",
            "AO" => "https://flagpedia.net/data/flags/w1160/ao.webp",
            "AQ" => "https://flagpedia.net/data/flags/w1160/aq.webp",
            "AR" => "https://flagpedia.net/data/flags/w1160/ar.webp",
            "AS" => "https://flagpedia.net/data/flags/w1160/as.webp",
            "AT" => "https://flagpedia.net/data/flags/w1160/at.webp",
            "AU" => "https://flagpedia.net/data/flags/w1160/au.webp",
            "AW" => "https://flagpedia.net/data/flags/w1160/aw.webp",
            "AX" => "https://flagpedia.net/data/flags/w1160/ax.webp",
            "AZ" => "https://flagpedia.net/data/flags/w1160/az.webp",
            "BA" => "https://flagpedia.net/data/flags/w1160/ba.webp",
            "BB" => "https://flagpedia.net/data/flags/w1160/bb.webp",
            "BD" => "https://flagpedia.net/data/flags/w1160/bd.webp",
            "BE" => "https://flagpedia.net/data/flags/w1160/be.webp",
            "BF" => "https://flagpedia.net/data/flags/w1160/bf.webp",
            "BG" => "https://flagpedia.net/data/flags/w1160/bg.webp",
            "BH" => "https://flagpedia.net/data/flags/w1160/bh.webp",
            "BI" => "https://flagpedia.net/data/flags/w1160/bi.webp",
            "BJ" => "https://flagpedia.net/data/flags/w1160/bj.webp",
            "BN" => "https://flagpedia.net/data/flags/w1160/bn.webp",
            "BO" => "https://flagpedia.net/data/flags/w1160/bo.webp",
            "BR" => "https://flagpedia.net/data/flags/w1160/br.webp",
            "BS" => "https://flagpedia.net/data/flags/w1160/bs.webp",
            "BT" => "https://flagpedia.net/data/flags/w1160/bt.webp",
            "BW" => "https://flagpedia.net/data/flags/w1160/bw.webp",
            "BY" => "https://flagpedia.net/data/flags/w1160/by.webp",
            "BZ" => "https://flagpedia.net/data/flags/w1160/bz.webp",
            "CA" => "https://flagpedia.net/data/flags/w1160/ca.webp",
            "CC" => "https://flagpedia.net/data/flags/w1160/cc.webp",
            "CD" => "https://flagpedia.net/data/flags/w1160/cd.webp",
            "CF" => "https://flagpedia.net/data/flags/w1160/cf.webp",
            "CG" => "https://flagpedia.net/data/flags/w1160/cg.webp",
            "CH" => "https://flagpedia.net/data/flags/w1160/ch.webp",
            "CI" => "https://flagpedia.net/data/flags/w1160/ci.webp",
            "CL" => "https://flagpedia.net/data/flags/w1160/cl.webp",
            "CM" => "https://flagpedia.net/data/flags/w1160/cm.webp",
            "CN" => "https://flagpedia.net/data/flags/w1160/cn.webp",
            "CO" => "https://flagpedia.net/data/flags/w1160/co.webp",
            "CR" => "https://flagpedia.net/data/flags/w1160/cr.webp",
            "CU" => "https://flagpedia.net/data/flags/w1160/cu.webp",
            "CV" => "https://flagpedia.net/data/flags/w1160/cv.webp",
            "CW" => "https://flagpedia.net/data/flags/w1160/cw.webp",
            "CX" => "https://flagpedia.net/data/flags/w1160/cx.webp",
            "CY" => "https://flagpedia.net/data/flags/w1160/cy.webp",
            "CZ" => "https://flagpedia.net/data/flags/w1160/cz.webp",
            "DE" => "https://flagpedia.net/data/flags/w1160/de.webp",
            "DJ" => "https://flagpedia.net/data/flags/w1160/dj.webp",
            "DK" => "https://flagpedia.net/data/flags/w1160/dk.webp",
            "DM" => "https://flagpedia.net/data/flags/w1160/dm.webp",
            "DO" => "https://flagpedia.net/data/flags/w1160/do.webp",
            "DZ" => "https://flagpedia.net/data/flags/w1160/dz.webp",
            "EC" => "https://flagpedia.net/data/flags/w1160/ec.webp",
            "EE" => "https://flagpedia.net/data/flags/w1160/ee.webp",
            "EG" => "https://flagpedia.net/data/flags/w1160/eg.webp",
            "EH" => "https://flagpedia.net/data/flags/w1160/eh.webp",
            "ER" => "https://flagpedia.net/data/flags/w1160/er.webp",
            "ES" => "https://flagpedia.net/data/flags/w1160/es.webp",
            "ET" => "https://flagpedia.net/data/flags/w1160/et.webp",
            "FI" => "https://flagpedia.net/data/flags/w1160/fi.webp",
            "FJ" => "https://flagpedia.net/data/flags/w1160/fj.webp",
            "FM" => "https://flagpedia.net/data/flags/w1160/fm.webp",
            "FO" => "https://flagpedia.net/data/flags/w1160/fo.webp",
            "FR" => "https://flagpedia.net/data/flags/w1160/fr.webp",
            "GA" => "https://flagpedia.net/data/flags/w1160/ga.webp",
            "GB" => "https://flagpedia.net/data/flags/w1160/gb.webp",
            "GD" => "https://flagpedia.net/data/flags/w1160/gd.webp",
            "GE" => "https://flagpedia.net/data/flags/w1160/ge.webp",
            "GF" => "https://flagpedia.net/data/flags/w1160/gf.webp",
            "GH" => "https://flagpedia.net/data/flags/w1160/gh.webp",
            "GI" => "https://flagpedia.net/data/flags/w1160/gi.webp",
            "GL" => "https://flagpedia.net/data/flags/w1160/gl.webp",
            "GM" => "https://flagpedia.net/data/flags/w1160/gm.webp",
            "GN" => "https://flagpedia.net/data/flags/w1160/gn.webp",
            "GQ" => "https://flagpedia.net/data/flags/w1160/gq.webp",
            "GR" => "https://flagpedia.net/data/flags/w1160/gr.webp",
            "GS" => "https://flagpedia.net/data/flags/w1160/gs.webp",
            "GT" => "https://flagpedia.net/data/flags/w1160/gt.webp",
            "GU" => "https://flagpedia.net/data/flags/w1160/gu.webp",
            "GW" => "https://flagpedia.net/data/flags/w1160/gw.webp",
            "GY" => "https://flagpedia.net/data/flags/w1160/gy.webp",
            "HK" => "https://flagpedia.net/data/flags/w1160/hk.webp",
            "HN" => "https://flagpedia.net/data/flags/w1160/hn.webp",
            "HR" => "https://flagpedia.net/data/flags/w1160/hr.webp",
            "HT" => "https://flagpedia.net/data/flags/w1160/ht.webp",
            "HU" => "https://flagpedia.net/data/flags/w1160/hu.webp",
            "ID" => "https://flagpedia.net/data/flags/w1160/id.webp",
            "IE" => "https://flagpedia.net/data/flags/w1160/ie.webp",
            "IL" => "https://flagpedia.net/data/flags/w1160/il.webp",
            "IM" => "https://flagpedia.net/data/flags/w1160/im.webp",
            "IN" => "https://flagpedia.net/data/flags/w1160/in.webp",
            "IQ" => "https://flagpedia.net/data/flags/w1160/iq.webp",
            "IR" => "https://flagpedia.net/data/flags/w1160/ir.webp",
            "IS" => "https://flagpedia.net/data/flags/w1160/is.webp",
            "IT" => "https://flagpedia.net/data/flags/w1160/it.webp",
            "JE" => "https://flagpedia.net/data/flags/w1160/je.webp",
            "JM" => "https://flagpedia.net/data/flags/w1160/jm.webp",
            "JO" => "https://flagpedia.net/data/flags/w1160/jo.webp",
            "JP" => "https://flagpedia.net/data/flags/w1160/jp.webp",
            "KE" => "https://flagpedia.net/data/flags/w1160/ke.webp",
            "KG" => "https://flagpedia.net/data/flags/w1160/kg.webp",
            "KH" => "https://flagpedia.net/data/flags/w1160/kh.webp",
            "KI" => "https://flagpedia.net/data/flags/w1160/ki.webp",
            "KM" => "https://flagpedia.net/data/flags/w1160/km.webp",
            "KN" => "https://flagpedia.net/data/flags/w1160/kn.webp",
            "KP" => "https://flagpedia.net/data/flags/w1160/kp.webp",
            "KR" => "https://flagpedia.net/data/flags/w1160/kr.webp",
            "KW" => "https://flagpedia.net/data/flags/w1160/kw.webp",
            "KZ" => "https://flagpedia.net/data/flags/w1160/kz.webp",
            "LA" => "https://flagpedia.net/data/flags/w1160/la.webp",
            "LB" => "https://flagpedia.net/data/flags/w1160/lb.webp",
            "LC" => "https://flagpedia.net/data/flags/w1160/lc.webp",
            "LI" => "https://flagpedia.net/data/flags/w1160/li.webp",
            "LK" => "https://flagpedia.net/data/flags/w1160/lk.webp",
            "LR" => "https://flagpedia.net/data/flags/w1160/lr.webp",
            "LS" => "https://flagpedia.net/data/flags/w1160/ls.webp",
            "LT" => "https://flagpedia.net/data/flags/w1160/lt.webp",
            "LU" => "https://flagpedia.net/data/flags/w1160/lu.webp",
            "LV" => "https://flagpedia.net/data/flags/w1160/lv.webp",
            "LY" => "https://flagpedia.net/data/flags/w1160/ly.webp",
            "MA" => "https://flagpedia.net/data/flags/w1160/ma.webp",
            "MC" => "https://flagpedia.net/data/flags/w1160/mc.webp",
            "MD" => "https://flagpedia.net/data/flags/w1160/md.webp",
            "ME" => "https://flagpedia.net/data/flags/w1160/me.webp",
            "MF" => "https://flagpedia.net/data/flags/w1160/mf.webp",
            "MG" => "https://flagpedia.net/data/flags/w1160/mg.webp",
            "MH" => "https://flagpedia.net/data/flags/w1160/mh.webp",
            "MK" => "https://flagpedia.net/data/flags/w1160/mk.webp",
            "ML" => "https://flagpedia.net/data/flags/w1160/ml.webp",
            "MM" => "https://flagpedia.net/data/flags/w1160/mm.webp",
            "MN" => "https://flagpedia.net/data/flags/w1160/mn.webp",
            "MO" => "https://flagpedia.net/data/flags/w1160/mo.webp",
            "MR" => "https://flagpedia.net/data/flags/w1160/mr.webp",
            "MT" => "https://flagpedia.net/data/flags/w1160/mt.webp",
            "MU" => "https://flagpedia.net/data/flags/w1160/mu.webp",
            "MV" => "https://flagpedia.net/data/flags/w1160/mv.webp",
            "MW" => "https://flagpedia.net/data/flags/w1160/mw.webp",
            "MX" => "https://flagpedia.net/data/flags/w1160/mx.webp",
            "MY" => "https://flagpedia.net/data/flags/w1160/my.webp",
            "MZ" => "https://flagpedia.net/data/flags/w1160/mz.webp",
            "NA" => "https://flagpedia.net/data/flags/w1160/na.webp",
            "NC" => "https://flagpedia.net/data/flags/w1160/nc.webp",
            "NE" => "https://flagpedia.net/data/flags/w1160/ne.webp",
            "NG" => "https://flagpedia.net/data/flags/w1160/ng.webp",
            "NI" => "https://flagpedia.net/data/flags/w1160/ni.webp",
            "NL" => "https://flagpedia.net/data/flags/w1160/nl.webp",
            "NO" => "https://flagpedia.net/data/flags/w1160/no.webp",
            "NP" => "https://flagpedia.net/data/flags/w1160/np.webp",
            "NR" => "https://flagpedia.net/data/flags/w1160/nr.webp",
            "NZ" => "https://flagpedia.net/data/flags/w1160/nz.webp",
            "OM" => "https://flagpedia.net/data/flags/w1160/om.webp",
            "PA" => "https://flagpedia.net/data/flags/w1160/pa.webp",
            "PE" => "https://flagpedia.net/data/flags/w1160/pe.webp",
            "PG" => "https://flagpedia.net/data/flags/w1160/pg.webp",
            "PH" => "https://flagpedia.net/data/flags/w1160/ph.webp",
            "PK" => "https://flagpedia.net/data/flags/w1160/pk.webp",
            "PL" => "https://flagpedia.net/data/flags/w1160/pl.webp",
            "PR" => "https://flagpedia.net/data/flags/w1160/pr.webp",
            "PS" => "https://flagpedia.net/data/flags/w1160/ps.webp",
            "PT" => "https://flagpedia.net/data/flags/w1160/pt.webp",
            "PW" => "https://flagpedia.net/data/flags/w1160/pw.webp",
            "PY" => "https://flagpedia.net/data/flags/w1160/py.webp",
            "QA" => "https://flagpedia.net/data/flags/w1160/qa.webp",
            "RO" => "https://flagpedia.net/data/flags/w1160/ro.webp",
            "RS" => "https://flagpedia.net/data/flags/w1160/rs.webp",
            "RU" => "https://flagpedia.net/data/flags/w1160/ru.webp",
            "RW" => "https://flagpedia.net/data/flags/w1160/rw.webp",
            "SA" => "https://flagpedia.net/data/flags/w1160/sa.webp",
            "SB" => "https://flagpedia.net/data/flags/w1160/sb.webp",
            "SC" => "https://flagpedia.net/data/flags/w1160/sc.webp",
            "SD" => "https://flagpedia.net/data/flags/w1160/sd.webp",
            "SG" => "https://flagpedia.net/data/flags/w1160/sg.webp",
            "SH" => "https://flagpedia.net/data/flags/w1160/sh.webp",
            "SI" => "https://flagpedia.net/data/flags/w1160/si.webp",
            "SK" => "https://flagpedia.net/data/flags/w1160/sk.webp",
            "SL" => "https://flagpedia.net/data/flags/w1160/sl.webp",
            "SM" => "https://flagpedia.net/data/flags/w1160/sm.webp",
            "SN" => "https://flagpedia.net/data/flags/w1160/sn.webp",
            "SO" => "https://flagpedia.net/data/flags/w1160/so.webp",
            "SR" => "https://flagpedia.net/data/flags/w1160/sr.webp",
            "ST" => "https://flagpedia.net/data/flags/w1160/st.webp",
            "SV" => "https://flagpedia.net/data/flags/w1160/sv.webp",
            "SY" => "https://flagpedia.net/data/flags/w1160/sy.webp",
            "TD" => "https://flagpedia.net/data/flags/w1160/td.webp",
            "TG" => "https://flagpedia.net/data/flags/w1160/tg.webp",
            "TH" => "https://flagpedia.net/data/flags/w1160/th.webp",
            "TJ" => "https://flagpedia.net/data/flags/w1160/tj.webp",
            "TL" => "https://flagpedia.net/data/flags/w1160/tl.webp",
            "TM" => "https://flagpedia.net/data/flags/w1160/tm.webp",
            "TN" => "https://flagpedia.net/data/flags/w1160/tn.webp",
            "TO" => "https://flagpedia.net/data/flags/w1160/to.webp",
            "TR" => "https://flagpedia.net/data/flags/w1160/tr.webp",
            "TT" => "https://flagpedia.net/data/flags/w1160/tt.webp",
            "TV" => "https://flagpedia.net/data/flags/w1160/tv.webp",
            "TZ" => "https://flagpedia.net/data/flags/w1160/tz.webp",
            "UA" => "https://flagpedia.net/data/flags/w1160/ua.webp",
            "UG" => "https://flagpedia.net/data/flags/w1160/ug.webp",
            "US" => "https://flagpedia.net/data/flags/w1160/us.webp",
            "UY" => "https://flagpedia.net/data/flags/w1160/uy.webp",
            "UZ" => "https://flagpedia.net/data/flags/w1160/uz.webp",
            "VA" => "https://flagpedia.net/data/flags/w1160/va.webp",
            "VC" => "https://flagpedia.net/data/flags/w1160/vc.webp",
            "VE" => "https://flagpedia.net/data/flags/w1160/ve.webp",
            "VN" => "https://flagpedia.net/data/flags/w1160/vn.webp",
            "VU" => "https://flagpedia.net/data/flags/w1160/vu.webp",
            "WS" => "https://flagpedia.net/data/flags/w1160/ws.webp",
            "YE" => "https://flagpedia.net/data/flags/w1160/ye.webp",
            "ZA" => "https://flagpedia.net/data/flags/w1160/za.webp",
            "ZM" => "https://flagpedia.net/data/flags/w1160/zm.webp",
            "ZW" => "https://flagpedia.net/data/flags/w1160/zw.webp",
        ];
        $country = new \App\Models\Country;

        foreach ($flags as $key => $value) {
            # code...
            $country->where('iso2',$key)->update([
                'flag_url'=>$value
            ]);
        }
    }
}
