<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\State;

class StateSeeder extends Seeder
{
    public function run()
    {
        $states = [
            // USA
            ['name' => 'California', 'country_id' => 1],
            ['name' => 'Texas', 'country_id' => 1],
            ['name' => 'New York', 'country_id' => 1],
            ['name' => 'Florida', 'country_id' => 1],
            ['name' => 'Illinois', 'country_id' => 1],
            ['name' => 'Ohio', 'country_id' => 1],
            ['name' => 'Alabama', 'country_id' => 1],
            ['name' => 'Alaska', 'country_id' => 1],
            ['name' => 'Arizona', 'country_id' => 1],
            ['name' => 'Arkansas', 'country_id' => 1],
            ['name' => 'California', 'country_id' => 1],
            ['name' => 'Colorado', 'country_id' => 1],
            ['name' => 'Connecticut', 'country_id' => 1],
            ['name' => 'Delaware', 'country_id' => 1],
            ['name' => 'Florida', 'country_id' => 1],
            ['name' => 'Georgia', 'country_id' => 1],
            ['name' => 'Hawaii', 'country_id' => 1],
            ['name' => 'Idaho', 'country_id' => 1],
            ['name' => 'Illinois', 'country_id' => 1],
            ['name' => 'Indiana', 'country_id' => 1],
            ['name' => 'Iowa', 'country_id' => 1],
            ['name' => 'Kansas', 'country_id' => 1],
            ['name' => 'Kentucky', 'country_id' => 1],
            ['name' => 'Louisiana', 'country_id' => 1],
            ['name' => 'Maine', 'country_id' => 1],
            ['name' => 'Maryland', 'country_id' => 1],
            ['name' => 'Massachusetts', 'country_id' => 1],
            ['name' => 'Michigan', 'country_id' => 1],
            ['name' => 'Minnesota', 'country_id' => 1],
            ['name' => 'Mississippi', 'country_id' => 1],
            ['name' => 'Missouri', 'country_id' => 1],
            ['name' => 'Montana', 'country_id' => 1],
            ['name' => 'Nebraska', 'country_id' => 1],
            ['name' => 'Nevada', 'country_id' => 1],
            ['name' => 'New Hampshire', 'country_id' => 1],
            ['name' => 'New Jersey', 'country_id' => 1],
            ['name' => 'New Mexico', 'country_id' => 1],
            ['name' => 'New York', 'country_id' => 1],
            ['name' => 'North Carolina', 'country_id' => 1],
            ['name' => 'North Dakota', 'country_id' => 1],
            ['name' => 'Ohio', 'country_id' => 1],
            ['name' => 'Oklahoma', 'country_id' => 1],
            ['name' => 'Oregon', 'country_id' => 1],
            ['name' => 'Pennsylvania', 'country_id' => 1],
            ['name' => 'Rhode Island', 'country_id' => 1],
            ['name' => 'South Carolina', 'country_id' => 1],
            ['name' => 'South Dakota', 'country_id' => 1],
            ['name' => 'Tennessee', 'country_id' => 1],
            ['name' => 'Texas', 'country_id' => 1],
            ['name' => 'Utah', 'country_id' => 1],
            ['name' => 'Vermont', 'country_id' => 1],
            ['name' => 'Virginia', 'country_id' => 1],
            ['name' => 'Washington', 'country_id' => 1],
            ['name' => 'West Virginia', 'country_id' => 1],
            ['name' => 'Wisconsin', 'country_id' => 1],
            ['name' => 'Wyoming', 'country_id' => 1],


            // Canada
            ['name' => 'Ontario', 'country_id' => 2],
            ['name' => 'Quebec', 'country_id' => 2],
            ['name' => 'British Columbia', 'country_id' => 2],
            ['name' => 'Alberta', 'country_id' => 2],
            ['name' => 'Manitoba', 'country_id' => 2],
            ['name' => 'Saskatchewan', 'country_id' => 2],
            ['name' => 'Nova Scotia', 'country_id' => 2],
            ['name' => 'New Brunswick', 'country_id' => 2],
            ['name' => 'Newfoundland and Labrador', 'country_id' => 2],
            ['name' => 'Prince Edward Island', 'country_id' => 2],
            ['name' => 'Northwest Territories', 'country_id' => 2],
            ['name' => 'Yukon', 'country_id' => 2],
            ['name' => 'Nunavut', 'country_id' => 2],

            // India
            ['name' => 'Maharashtra', 'country_id' => 3],
            ['name' => 'Karnataka', 'country_id' => 3],
            ['name' => 'Tamil Nadu', 'country_id' => 3],
            ['name' => 'Uttar Pradesh', 'country_id' => 3],
            ['name' => 'Delhi', 'country_id' => 3],
            ['name' => 'West Bengal', 'country_id' => 3],
            ['name' => 'Gujarat', 'country_id' => 3],
            ['name' => 'Rajasthan', 'country_id' => 3],
            ['name' => 'Bihar', 'country_id' => 3],
            ['name' => 'Andhra Pradesh', 'country_id' => 3],
            ['name' => 'Madhya Pradesh', 'country_id' => 3],
            ['name' => 'Haryana', 'country_id' => 3],
            ['name' => 'Punjab', 'country_id' => 3],
            ['name' => 'Chhattisgarh', 'country_id' => 3],
            ['name' => 'Odisha', 'country_id' => 3],
            ['name' => 'Kerala', 'country_id' => 3],
            ['name' => 'Jharkhand', 'country_id' => 3],
            ['name' => 'Assam', 'country_id' => 3],
            ['name' => 'Uttarakhand', 'country_id' => 3],
            ['name' => 'Goa', 'country_id' => 3],
            ['name' => 'Nagaland', 'country_id' => 3],
            ['name' => 'Sikkim', 'country_id' => 3],
            ['name' => 'Tripura', 'country_id' => 3],
            ['name' => 'Meghalaya', 'country_id' => 3],
            ['name' => 'Manipur', 'country_id' => 3],
            ['name' => 'Arunachal Pradesh', 'country_id' => 3],
            ['name' => 'Mizoram', 'country_id' => 3],
            ['name' => 'Nagaland', 'country_id' => 3],
            ['name' => 'Himachal Pradesh', 'country_id' => 3],
            ['name' => 'Andaman and Nicobar Islands', 'country_id' => 3],
            ['name' => 'Lakshadweep', 'country_id' => 3],


            // Nigeria 🇳🇬
            ['name' => 'Abia', 'country_id' => 4],
            ['name' => 'Adamawa', 'country_id' => 4],
            ['name' => 'Akwa Ibom', 'country_id' => 4],
            ['name' => 'Anambra', 'country_id' => 4],
            ['name' => 'Bauchi', 'country_id' => 4],
            ['name' => 'Bayelsa', 'country_id' => 4],
            ['name' => 'Benue', 'country_id' => 4],
            ['name' => 'Borno', 'country_id' => 4],
            ['name' => 'Cross River', 'country_id' => 4],
            ['name' => 'Delta', 'country_id' => 4],
            ['name' => 'Ebonyi', 'country_id' => 4],
            ['name' => 'Edo', 'country_id' => 4],
            ['name' => 'Ekiti', 'country_id' => 4],
            ['name' => 'Enugu', 'country_id' => 4],
            ['name' => 'Gombe', 'country_id' => 4],
            ['name' => 'Imo', 'country_id' => 4],
            ['name' => 'Jigawa', 'country_id' => 4],
            ['name' => 'Kaduna', 'country_id' => 4],
            ['name' => 'Kano', 'country_id' => 4],
            ['name' => 'Katsina', 'country_id' => 4],
            ['name' => 'Kebbi', 'country_id' => 4],
            ['name' => 'Kogi', 'country_id' => 4],
            ['name' => 'Kwara', 'country_id' => 4],
            ['name' => 'Lagos', 'country_id' => 4],
            ['name' => 'Nasarawa', 'country_id' => 4],
            ['name' => 'Niger', 'country_id' => 4],
            ['name' => 'Ogun', 'country_id' => 4],
            ['name' => 'Ondo', 'country_id' => 4],
            ['name' => 'Osun', 'country_id' => 4],
            ['name' => 'Oyo', 'country_id' => 4],
            ['name' => 'Plateau', 'country_id' => 4],
            ['name' => 'Rivers', 'country_id' => 4],
            ['name' => 'Sokoto', 'country_id' => 4],
            ['name' => 'Taraba', 'country_id' => 4],
            ['name' => 'Yobe', 'country_id' => 4],
            ['name' => 'Zamfara', 'country_id' => 4],
            ['name' => 'Federal Capital Territory (Abuja)', 'country_id' => 4],

            // South Africa 🇿🇦
            ['name' => 'Gauteng', 'country_id' => 5],
            ['name' => 'Western Cape', 'country_id' => 5],
            ['name' => 'KwaZulu-Natal', 'country_id' => 5],
            ['name' => 'Eastern Cape', 'country_id' => 5],
            ['name' => 'Limpopo', 'country_id' => 5],
            ['name' => 'Mpumalanga', 'country_id' => 5],
            ['name' => 'North West', 'country_id' => 5],
            ['name' => 'Northern Cape', 'country_id' => 5],
            ['name' => 'Free State', 'country_id' => 5],

            // Kenya 🇰🇪
            ['name' => 'Nairobi', 'country_id' => 6],
            ['name' => 'Mombasa', 'country_id' => 6],
            ['name' => 'Kisumu', 'country_id' => 6],
            ['name' => 'Nakuru', 'country_id' => 6],
            ['name' => 'Eldoret', 'country_id' => 6],
            ['name' => 'Thika', 'country_id' => 6],
            ['name' => 'Malindi', 'country_id' => 6],
            ['name' => 'Kitale', 'country_id' => 6],
            ['name' => 'Garissa', 'country_id' => 6],
            ['name' => 'Nyeri', 'country_id' => 6],
            ['name' => 'Meru', 'country_id' => 6],
            ['name' => 'Machakos', 'country_id' => 6],
            ['name' => 'Kericho', 'country_id' => 6],
            ['name' => 'Embu', 'country_id' => 6],
            ['name' => 'Kakamega', 'country_id' => 6],
            ['name' => 'Bungoma', 'country_id' => 6],
            ['name' => 'Narok', 'country_id' => 6],
            ['name' => 'Migori', 'country_id' => 6],
            ['name' => 'Lamu', 'country_id' => 6],
            ['name' => 'Isiolo', 'country_id' => 6],

            // Egypt 🇪🇬
            ['name' => 'Cairo', 'country_id' => 7],
            ['name' => 'Giza', 'country_id' => 7],
            ['name' => 'Alexandria', 'country_id' => 7],
            ['name' => 'Luxor', 'country_id' => 7],
            ['name' => 'Aswan', 'country_id' => 7],
            ['name' => 'Port Said', 'country_id' => 7],
            ['name' => 'Suez', 'country_id' => 7],
            ['name' => 'Ismailia', 'country_id' => 7],
            ['name' => 'Mansoura', 'country_id' => 7],
            ['name' => 'Tanta', 'country_id' => 7],
            ['name' => 'Faiyum', 'country_id' => 7],
            ['name' => 'Zagazig', 'country_id' => 7],
            ['name' => 'Minya', 'country_id' => 7],
            ['name' => 'Beni Suef', 'country_id' => 7],
            ['name' => 'Sohag', 'country_id' => 7],
            ['name' => 'Hurghada', 'country_id' => 7],
            ['name' => 'Sharm El-Sheikh', 'country_id' => 7],
            ['name' => 'Damanhur', 'country_id' => 7],
            ['name' => 'Damietta', 'country_id' => 7],
            ['name' => 'Qena', 'country_id' => 7],

            // Ghana 🇬🇭
            ['name' => 'Greater Accra', 'country_id' => 8],
            ['name' => 'Ashanti', 'country_id' => 8],
            ['name' => 'Western', 'country_id' => 8],
            ['name' => 'Central', 'country_id' => 8],
            ['name' => 'Eastern', 'country_id' => 8],
            ['name' => 'Volta', 'country_id' => 8],
            ['name' => 'Northern', 'country_id' => 8],
            ['name' => 'Upper East', 'country_id' => 8],
            ['name' => 'Upper West', 'country_id' => 8],
            ['name' => 'Bono', 'country_id' => 8],
            ['name' => 'Bono East', 'country_id' => 8],
            ['name' => 'Ahafo', 'country_id' => 8],
            ['name' => 'Western North', 'country_id' => 8],
            ['name' => 'Oti', 'country_id' => 8],
            ['name' => 'Savannah', 'country_id' => 8],
            ['name' => 'North East', 'country_id' => 8],

            // Ethiopia 🇪🇹
            ['name' => 'Addis Ababa', 'country_id' => 9], // Chartered City
            ['name' => 'Dire Dawa', 'country_id' => 9], // Chartered City
            ['name' => 'Oromia', 'country_id' => 9],
            ['name' => 'Amhara', 'country_id' => 9],
            ['name' => 'Tigray', 'country_id' => 9],
            ['name' => 'Sidama', 'country_id' => 9],
            ['name' => 'Afar', 'country_id' => 9],
            ['name' => 'Somali', 'country_id' => 9],
            ['name' => 'Benishangul-Gumuz', 'country_id' => 9],
            ['name' => 'Southern Nations, Nationalities, and Peoples\' Region (SNNPR)', 'country_id' => 9],
            ['name' => 'Gambela', 'country_id' => 9],
            ['name' => 'Harari', 'country_id' => 9],
            ['name' => 'South West Ethiopia Peoples\' Region', 'country_id' => 9],

            // Morocco 🇲🇦
            ['name' => 'Casablanca-Settat', 'country_id' => 10],
            ['name' => 'Marrakech-Safi', 'country_id' => 10],
            ['name' => 'Fès-Meknès', 'country_id' => 10],
            ['name' => 'Rabat-Salé-Kénitra', 'country_id' => 10],
            ['name' => 'Tangier-Tétouan-Al Hoceïma', 'country_id' => 10],
            ['name' => 'Drâa-Tafilalet', 'country_id' => 10],
            ['name' => 'Béni Mellal-Khénifra', 'country_id' => 10],
            ['name' => 'Souss-Massa', 'country_id' => 10],
            ['name' => 'Oriental', 'country_id' => 10],
            ['name' => 'Laâyoune-Sakia El Hamra', 'country_id' => 10],
            ['name' => 'Dakhla-Oued Ed-Dahab', 'country_id' => 10],
            ['name' => 'Guelmim-Oued Noun', 'country_id' => 10],

            // Tanzania 🇹🇿
            ['name' => 'Dar es Salaam', 'country_id' => 11],
            ['name' => 'Arusha', 'country_id' => 11],
            ['name' => 'Mwanza', 'country_id' => 11],
            ['name' => 'Mbeya', 'country_id' => 11],
            ['name' => 'Dodoma', 'country_id' => 11],
            ['name' => 'Kilimanjaro', 'country_id' => 11],
            ['name' => 'Tanga', 'country_id' => 11],
            ['name' => 'Morogoro', 'country_id' => 11],
            ['name' => 'Pwani', 'country_id' => 11],
            ['name' => 'Lindi', 'country_id' => 11],
            ['name' => 'Mtwara', 'country_id' => 11],
            ['name' => 'Ruvuma', 'country_id' => 11],
            ['name' => 'Iringa', 'country_id' => 11],
            ['name' => 'Singida', 'country_id' => 11],
            ['name' => 'Tabora', 'country_id' => 11],
            ['name' => 'Rukwa', 'country_id' => 11],
            ['name' => 'Kigoma', 'country_id' => 11],
            ['name' => 'Shinyanga', 'country_id' => 11],
            ['name' => 'Kagera', 'country_id' => 11],
            ['name' => 'Mara', 'country_id' => 11],
            ['name' => 'Manyara', 'country_id' => 11],
            ['name' => 'Njombe', 'country_id' => 11],
            ['name' => 'Katavi', 'country_id' => 11],
            ['name' => 'Geita', 'country_id' => 11],
            ['name' => 'Simiyu', 'country_id' => 11],
            ['name' => 'Songwe', 'country_id' => 11],
            ['name' => 'Unguja North', 'country_id' => 11], // Zanzibar
            ['name' => 'Unguja South', 'country_id' => 11], // Zanzibar
            ['name' => 'Zanzibar West', 'country_id' => 11], // Zanzibar
            ['name' => 'Pemba North', 'country_id' => 11], // Zanzibar
            ['name' => 'Pemba South', 'country_id' => 11], // Zanzibar

            // Australia 🇦🇺
            ['name' => 'New South Wales', 'country_id' => 12],
            ['name' => 'Queensland', 'country_id' => 12],
            ['name' => 'Victoria', 'country_id' => 12],
            ['name' => 'Western Australia', 'country_id' => 12],
            ['name' => 'South Australia', 'country_id' => 12],
            ['name' => 'Tasmania', 'country_id' => 12],
            ['name' => 'Australian Capital Territory', 'country_id' => 12], // Territory
            ['name' => 'Northern Territory', 'country_id' => 12], // Territory

            // United Kingdom 🇬🇧
            ['name' => 'England', 'country_id' => 13],
            ['name' => 'Scotland', 'country_id' => 13],
            ['name' => 'Wales', 'country_id' => 13],
            ['name' => 'Northern Ireland', 'country_id' => 13],

            // Brazil 🇧🇷
            ['name' => 'Acre', 'country_id' => 14],
            ['name' => 'Alagoas', 'country_id' => 14],
            ['name' => 'Amapá', 'country_id' => 14],
            ['name' => 'Amazonas', 'country_id' => 14],
            ['name' => 'Bahia', 'country_id' => 14],
            ['name' => 'Ceará', 'country_id' => 14],
            ['name' => 'Distrito Federal', 'country_id' => 14], // Federal District (Brasília)
            ['name' => 'Espírito Santo', 'country_id' => 14],
            ['name' => 'Goiás', 'country_id' => 14],
            ['name' => 'Maranhão', 'country_id' => 14],
            ['name' => 'Mato Grosso', 'country_id' => 14],
            ['name' => 'Mato Grosso do Sul', 'country_id' => 14],
            ['name' => 'Minas Gerais', 'country_id' => 14],
            ['name' => 'Pará', 'country_id' => 14],
            ['name' => 'Paraíba', 'country_id' => 14],
            ['name' => 'Paraná', 'country_id' => 14],
            ['name' => 'Pernambuco', 'country_id' => 14],
            ['name' => 'Piauí', 'country_id' => 14],
            ['name' => 'Rio de Janeiro', 'country_id' => 14],
            ['name' => 'Rio Grande do Norte', 'country_id' => 14],
            ['name' => 'Rio Grande do Sul', 'country_id' => 14],
            ['name' => 'Rondônia', 'country_id' => 14],
            ['name' => 'Roraima', 'country_id' => 14],
            ['name' => 'Santa Catarina', 'country_id' => 14],
            ['name' => 'São Paulo', 'country_id' => 14],
            ['name' => 'Sergipe', 'country_id' => 14],
            ['name' => 'Tocantins', 'country_id' => 14],
        ];

        State::insert($states);
    }
}
