UPDATE countries SET phone_length = 9 WHERE name = 'Afghanistan';
UPDATE countries SET phone_length = 10 WHERE name = 'Aland Islands';
UPDATE countries SET phone_length = 9 WHERE name = 'Albania';
UPDATE countries SET phone_length = 9 WHERE name = 'Algeria';
UPDATE countries SET phone_length = 10 WHERE name = 'American Samoa';
UPDATE countries SET phone_length = 6 WHERE name = 'Andorra';
UPDATE countries SET phone_length = 9 WHERE name = 'Angola';
UPDATE countries SET phone_length = 7 WHERE name = 'Anguilla';
UPDATE countries SET phone_length = 7 WHERE name = 'Antarctica';
UPDATE countries SET phone_length = 7 WHERE name = 'Antigua and Barbuda';
UPDATE countries SET phone_length = 10 WHERE name = 'Argentina';
UPDATE countries SET phone_length = 8 WHERE name = 'Armenia';
UPDATE countries SET phone_length = 7 WHERE name = 'Aruba';
UPDATE countries SET phone_length = 9 WHERE name = 'Australia';
UPDATE countries SET phone_length = 10 WHERE name = 'Austria';
UPDATE countries SET phone_length = 9 WHERE name = 'Azerbaijan';
UPDATE countries SET phone_length = 7 WHERE name = 'The Bahamas';
UPDATE countries SET phone_length = 8 WHERE name = 'Bahrain';
UPDATE countries SET phone_length = 10 WHERE name = 'Bangladesh';
UPDATE countries SET phone_length = 7 WHERE name = 'Barbados';
UPDATE countries SET phone_length = 9 WHERE name = 'Belarus';
UPDATE countries SET phone_length = 9 WHERE name = 'Belgium';
UPDATE countries SET phone_length = 7 WHERE name = 'Belize';
UPDATE countries SET phone_length = 8 WHERE name = 'Benin';
UPDATE countries SET phone_length = 7 WHERE name = 'Bermuda';
UPDATE countries SET phone_length = 8 WHERE name = 'Bhutan';
UPDATE countries SET phone_length = 8 WHERE name = 'Bolivia';
UPDATE countries SET phone_length = 8 WHERE name = 'Bosnia and Herzegovina';
UPDATE countries SET phone_length = 8 WHERE name = 'Botswana';
UPDATE countries SET phone_length = 10 WHERE name = 'Bouvet Island';
UPDATE countries SET phone_length = 10 WHERE name = 'Brazil';
UPDATE countries SET phone_length = 7 WHERE name = 'British Indian Ocean Territory';
UPDATE countries SET phone_length = 7 WHERE name = 'Brunei';
UPDATE countries SET phone_length = 9 WHERE name = 'Bulgaria';
UPDATE countries SET phone_length = 8 WHERE name = 'Burkina Faso';
UPDATE countries SET phone_length = 8 WHERE name = 'Burundi';
UPDATE countries SET phone_length = 9 WHERE name = 'Cambodia';
UPDATE countries SET phone_length = 9 WHERE name = 'Cameroon';
UPDATE countries SET phone_length = 10 WHERE name = 'Canada';
UPDATE countries SET phone_length = 7 WHERE name = 'Cape Verde';
UPDATE countries SET phone_length = 7 WHERE name = 'Cayman Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Central African Republic';
UPDATE countries SET phone_length = 8 WHERE name = 'Chad';
UPDATE countries SET phone_length = 9 WHERE name = 'Chile';
UPDATE countries SET phone_length = 11 WHERE name = 'China';
UPDATE countries SET phone_length = 6 WHERE name = 'Christmas Island';
UPDATE countries SET phone_length = 6 WHERE name = 'Cocos (Keeling) Islands';
UPDATE countries SET phone_length = 10 WHERE name = 'Colombia';
UPDATE countries SET phone_length = 7 WHERE name = 'Comoros';
UPDATE countries SET phone_length = 9 WHERE name = 'Congo';
UPDATE countries SET phone_length = 9 WHERE name = 'Democratic Republic of the Congo';
UPDATE countries SET phone_length = 5 WHERE name = 'Cook Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Costa Rica';
UPDATE countries SET phone_length = 8 WHERE name = 'Cote D\'Ivoire (Ivory Coast)';
UPDATE countries SET phone_length = 9 WHERE name = 'Croatia';
UPDATE countries SET phone_length = 8 WHERE name = 'Cuba';
UPDATE countries SET phone_length = 8 WHERE name = 'Cyprus';
UPDATE countries SET phone_length = 9 WHERE name = 'Czech Republic';
UPDATE countries SET phone_length = 8 WHERE name = 'Denmark';
UPDATE countries SET phone_length = 8 WHERE name = 'Djibouti';
UPDATE countries SET phone_length = 7 WHERE name = 'Dominica';
UPDATE countries SET phone_length = 10 WHERE name = 'Dominican Republic';
UPDATE countries SET phone_length = 7 WHERE name = 'Timor-Leste';
UPDATE countries SET phone_length = 9 WHERE name = 'Ecuador';
UPDATE countries SET phone_length = 10 WHERE name = 'Egypt';
UPDATE countries SET phone_length = 8 WHERE name = 'El Salvador';
UPDATE countries SET phone_length = 9 WHERE name = 'Equatorial Guinea';
UPDATE countries SET phone_length = 7 WHERE name = 'Eritrea';
UPDATE countries SET phone_length = 7 WHERE name = 'Estonia';
UPDATE countries SET phone_length = 9 WHERE name = 'Ethiopia';
UPDATE countries SET phone_length = 5 WHERE name = 'Falkland Islands';
UPDATE countries SET phone_length = 6 WHERE name = 'Faroe Islands';
UPDATE countries SET phone_length = 7 WHERE name = 'Fiji Islands';
UPDATE countries SET phone_length = 9 WHERE name = 'Finland';
UPDATE countries SET phone_length = 9 WHERE name = 'France';
UPDATE countries SET phone_length = 9 WHERE name = 'French Guiana';
UPDATE countries SET phone_length = 6 WHERE name = 'French Polynesia';
UPDATE countries SET phone_length = 7 WHERE name = 'French Southern Territories';
UPDATE countries SET phone_length = 8 WHERE name = 'Gabon';
UPDATE countries SET phone_length = 7 WHERE name = 'The Gambia ';
UPDATE countries SET phone_length = 9 WHERE name = 'Georgia';
UPDATE countries SET phone_length = 11 WHERE name = 'Germany';
UPDATE countries SET phone_length = 10 WHERE name = 'Ghana';
UPDATE countries SET phone_length = 8 WHERE name = 'Gibraltar';
UPDATE countries SET phone_length = 10 WHERE name = 'Greece';
UPDATE countries SET phone_length = 6 WHERE name = 'Greenland';
UPDATE countries SET phone_length = 7 WHERE name = 'Grenada';
UPDATE countries SET phone_length = 9 WHERE name = 'Guadeloupe';
UPDATE countries SET phone_length = 7 WHERE name = 'Guam';
UPDATE countries SET phone_length = 8 WHERE name = 'Guatemala';
UPDATE countries SET phone_length = 6 WHERE name = 'Guernsey';
UPDATE countries SET phone_length = 9 WHERE name = 'Guinea';
UPDATE countries SET phone_length = 7 WHERE name = 'Guinea-Bissau';
UPDATE countries SET phone_length = 7 WHERE name = 'Guyana';
UPDATE countries SET phone_length = 8 WHERE name = 'Haiti';
UPDATE countries SET phone_length = 6 WHERE name = 'Heard Island and McDonald Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Honduras';
UPDATE countries SET phone_length = 8 WHERE name = 'Hong Kong S.A.R.';
UPDATE countries SET phone_length = 9 WHERE name = 'Hungary';
UPDATE countries SET phone_length = 7 WHERE name = 'Iceland';
UPDATE countries SET phone_length = 10 WHERE name = 'India';
UPDATE countries SET phone_length = 10 WHERE name = 'Indonesia';
UPDATE countries SET phone_length = 10 WHERE name = 'Iran';
UPDATE countries SET phone_length = 10 WHERE name = 'Iraq';
UPDATE countries SET phone_length = 9 WHERE name = 'Ireland';
UPDATE countries SET phone_length = 9 WHERE name = 'Israel';
UPDATE countries SET phone_length = 10 WHERE name = 'Italy';
UPDATE countries SET phone_length = 7 WHERE name = 'Jamaica';
UPDATE countries SET phone_length = 10 WHERE name = 'Japan';
UPDATE countries SET phone_length = 9 WHERE name = 'Jersey';
UPDATE countries SET phone_length = 9 WHERE name = 'Jordan';
UPDATE countries SET phone_length = 10 WHERE name = 'Kazakhstan';
UPDATE countries SET phone_length = 9 WHERE name = 'Kenya';
UPDATE countries SET phone_length = 8 WHERE name = 'Kiribati';
UPDATE countries SET phone_length = 8 WHERE name = 'North Korea';
UPDATE countries SET phone_length = 9 WHERE name = 'South Korea';
UPDATE countries SET phone_length = 8 WHERE name = 'Kuwait';
UPDATE countries SET phone_length = 9 WHERE name = 'Kyrgyzstan';
UPDATE countries SET phone_length = 10 WHERE name = 'Laos';
UPDATE countries SET phone_length = 8 WHERE name = 'Latvia';
UPDATE countries SET phone_length = 8 WHERE name = 'Lebanon';
UPDATE countries SET phone_length = 8 WHERE name = 'Lesotho';
UPDATE countries SET phone_length = 8 WHERE name = 'Liberia';
UPDATE countries SET phone_length = 9 WHERE name = 'Libya';
UPDATE countries SET phone_length = 7 WHERE name = 'Liechtenstein';
UPDATE countries SET phone_length = 8 WHERE name = 'Lithuania';
UPDATE countries SET phone_length = 9 WHERE name = 'Luxembourg';
UPDATE countries SET phone_length = 8 WHERE name = 'Macau S.A.R.';
UPDATE countries SET phone_length = 8 WHERE name = 'North Macedonia';
UPDATE countries SET phone_length = 9 WHERE name = 'Madagascar';
UPDATE countries SET phone_length = 9 WHERE name = 'Malawi';
UPDATE countries SET phone_length = 9 WHERE name = 'Malaysia';
UPDATE countries SET phone_length = 7 WHERE name = 'Maldives';
UPDATE countries SET phone_length = 8 WHERE name = 'Mali';
UPDATE countries SET phone_length = 8 WHERE name = 'Malta';
UPDATE countries SET phone_length = 8 WHERE name = 'Man (Isle of)';
UPDATE countries SET phone_length = 7 WHERE name = 'Marshall Islands';
UPDATE countries SET phone_length = 9 WHERE name = 'Martinique';
UPDATE countries SET phone_length = 8 WHERE name = 'Mauritania';
UPDATE countries SET phone_length = 7 WHERE name = 'Mauritius';
UPDATE countries SET phone_length = 5 WHERE name = 'Mayotte';
UPDATE countries SET phone_length = 10 WHERE name = 'Mexico';
UPDATE countries SET phone_length = 7 WHERE name = 'Micronesia';
UPDATE countries SET phone_length = 8 WHERE name = 'Moldova';
UPDATE countries SET phone_length = 8 WHERE name = 'Monaco';
UPDATE countries SET phone_length = 8 WHERE name = 'Mongolia';
UPDATE countries SET phone_length = 8 WHERE name = 'Montenegro';
UPDATE countries SET phone_length = 7 WHERE name = 'Montserrat';
UPDATE countries SET phone_length = 9 WHERE name = 'Morocco';
UPDATE countries SET phone_length = 9 WHERE name = 'Mozambique';
UPDATE countries SET phone_length = 9 WHERE name = 'Myanmar';
UPDATE countries SET phone_length = 9 WHERE name = 'Namibia';
UPDATE countries SET phone_length = 7 WHERE name = 'Nauru';
UPDATE countries SET phone_length = 10 WHERE name = 'Nepal';
UPDATE countries SET phone_length = 7 WHERE name = 'Bonaire, Sint Eustatius and Saba';
UPDATE countries SET phone_length = 9 WHERE name = 'Netherlands';
UPDATE countries SET phone_length = 6 WHERE name = 'New Caledonia';
UPDATE countries SET phone_length = 9 WHERE name = 'New Zealand';
UPDATE countries SET phone_length = 8 WHERE name = 'Nicaragua';
UPDATE countries SET phone_length = 8 WHERE name = 'Niger';
UPDATE countries SET phone_length = 8 WHERE name = 'Nigeria';
UPDATE countries SET phone_length = 4 WHERE name = 'Niue';
UPDATE countries SET phone_length = 6 WHERE name = 'Norfolk Island';
UPDATE countries SET phone_length = 10 WHERE name = 'Northern Mariana Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Norway';
UPDATE countries SET phone_length = 8 WHERE name = 'Oman';
UPDATE countries SET phone_length = 10 WHERE name = 'Pakistan';
UPDATE countries SET phone_length = 7 WHERE name = 'Palau';
UPDATE countries SET phone_length = 9 WHERE name = 'Palestinian Territory Occupied';
UPDATE countries SET phone_length = 8 WHERE name = 'Panama';
UPDATE countries SET phone_length = 8 WHERE name = 'Papua New Guinea';
UPDATE countries SET phone_length = 9 WHERE name = 'Paraguay';
UPDATE countries SET phone_length = 9 WHERE name = 'Peru';
UPDATE countries SET phone_length = 10 WHERE name = 'Philippines';
UPDATE countries SET phone_length = 4 WHERE name = 'Pitcairn Island';
UPDATE countries SET phone_length = 9 WHERE name = 'Poland';
UPDATE countries SET phone_length = 9 WHERE name = 'Portugal';
UPDATE countries SET phone_length = 10 WHERE name = 'Puerto Rico';
UPDATE countries SET phone_length = 8 WHERE name = 'Qatar';
UPDATE countries SET phone_length = 9 WHERE name = 'Reunion';
UPDATE countries SET phone_length = 10 WHERE name = 'Romania';
UPDATE countries SET phone_length = 10 WHERE name = 'Russia';
UPDATE countries SET phone_length = 9 WHERE name = 'Rwanda';
UPDATE countries SET phone_length = 5 WHERE name = 'Saint Helena';
UPDATE countries SET phone_length = 7 WHERE name = 'Saint Kitts and Nevis';
UPDATE countries SET phone_length = 7 WHERE name = 'Saint Lucia';
UPDATE countries SET phone_length = 6 WHERE name = 'Saint Pierre and Miquelon';
UPDATE countries SET phone_length = 7 WHERE name = 'Saint Vincent and the Grenadines';
UPDATE countries SET phone_length = 6 WHERE name = 'Saint-Barthelemy';
UPDATE countries SET phone_length = 6 WHERE name = 'Saint-Martin (French part)';
UPDATE countries SET phone_length = 7 WHERE name = 'Samoa';
UPDATE countries SET phone_length = 6 WHERE name = 'San Marino';
UPDATE countries SET phone_length = 7 WHERE name = 'Sao Tome and Principe';
UPDATE countries SET phone_length = 9 WHERE name = 'Saudi Arabia';
UPDATE countries SET phone_length = 9 WHERE name = 'Senegal';
UPDATE countries SET phone_length = 9 WHERE name = 'Serbia';
UPDATE countries SET phone_length = 7 WHERE name = 'Seychelles';
UPDATE countries SET phone_length = 8 WHERE name = 'Sierra Leone';
UPDATE countries SET phone_length = 8 WHERE name = 'Singapore';
UPDATE countries SET phone_length = 9 WHERE name = 'Slovakia';
UPDATE countries SET phone_length = 8 WHERE name = 'Slovenia';
UPDATE countries SET phone_length = 5 WHERE name = 'Solomon Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Somalia';
UPDATE countries SET phone_length = 9 WHERE name = 'South Africa';
UPDATE countries SET phone_length = 5 WHERE name = 'South Georgia';
UPDATE countries SET phone_length = 9 WHERE name = 'South Sudan';
UPDATE countries SET phone_length = 9 WHERE name = 'Spain';
UPDATE countries SET phone_length = 9 WHERE name = 'Sri Lanka';
UPDATE countries SET phone_length = 9 WHERE name = 'Sudan';
UPDATE countries SET phone_length = 7 WHERE name = 'Suriname';
UPDATE countries SET phone_length = 7 WHERE name = 'Svalbard and Jan Mayen Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Eswatini';
UPDATE countries SET phone_length = 9 WHERE name = 'Sweden';
UPDATE countries SET phone_length = 9 WHERE name = 'Switzerland';
UPDATE countries SET phone_length = 9 WHERE name = 'Syria';
UPDATE countries SET phone_length = 9 WHERE name = 'Taiwan';
UPDATE countries SET phone_length = 9 WHERE name = 'Tajikistan';
UPDATE countries SET phone_length = 9 WHERE name = 'Tanzania';
UPDATE countries SET phone_length = 9 WHERE name = 'Thailand';
UPDATE countries SET phone_length = 8 WHERE name = 'Togo';
UPDATE countries SET phone_length = 4 WHERE name = 'Tokelau';
UPDATE countries SET phone_length = 5 WHERE name = 'Tonga';
UPDATE countries SET phone_length = 7 WHERE name = 'Trinidad and Tobago';
UPDATE countries SET phone_length = 8 WHERE name = 'Tunisia';
UPDATE countries SET phone_length = 10 WHERE name = 'Turkey';
UPDATE countries SET phone_length = 9 WHERE name = 'Turkmenistan';
UPDATE countries SET phone_length = 7 WHERE name = 'Turks and Caicos Islands';
UPDATE countries SET phone_length = 5 WHERE name = 'Tuvalu';
UPDATE countries SET phone_length = 9 WHERE name = 'Uganda';
UPDATE countries SET phone_length = 9 WHERE name = 'Ukraine';
UPDATE countries SET phone_length = 9 WHERE name = 'United Arab Emirates';
UPDATE countries SET phone_length = 10 WHERE name = 'United Kingdom';
UPDATE countries SET phone_length = 10 WHERE name = 'United States';
UPDATE countries SET phone_length = 5 WHERE name = 'United States Minor Outlying Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Uruguay';
UPDATE countries SET phone_length = 9 WHERE name = 'Uzbekistan';
UPDATE countries SET phone_length = 7 WHERE name = 'Vanuatu';
UPDATE countries SET phone_length = 6 WHERE name = 'Vatican City State (Holy See)';
UPDATE countries SET phone_length = 10 WHERE name = 'Venezuela';
UPDATE countries SET phone_length = 10 WHERE name = 'Vietnam';
UPDATE countries SET phone_length = 7 WHERE name = 'Virgin Islands (British)';
UPDATE countries SET phone_length = 10 WHERE name = 'Virgin Islands (US)';
UPDATE countries SET phone_length = 6 WHERE name = 'Wallis and Futuna Islands';
UPDATE countries SET phone_length = 8 WHERE name = 'Western Sahara';
UPDATE countries SET phone_length = 9 WHERE name = 'Yemen';
UPDATE countries SET phone_length = 9 WHERE name = 'Zambia';
UPDATE countries SET phone_length = 9 WHERE name = 'Zimbabwe';
UPDATE countries SET phone_length = 8 WHERE name = 'Kosovo';
UPDATE countries SET phone_length = 7 WHERE name = 'Curaçao';
UPDATE countries SET phone_length = 7 WHERE name = 'Sint Maarten (Dutch part)';
UPDATE countries SET phone_length = 8 WHERE name = 'Côte d\'Ivoire';
